# Generated by Django 3.1 on 2020-08-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200829_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
